####  PBS preamble
#PBS -N raxml
#PBS -M rprops@umich.edu
#PBS -m abe

#PBS -l nodes=1:ppn=20,mem=500gb,walltime=10:00:00:00
#PBS -V

#PBS -A vdenef_fluxm
#PBS -l qos=flux
#PBS -q fluxm
####  End PBS preamble

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi

# RAxML  code is multithreaded using OpenMP in addition to pthreads.  On Flux, to use OpenMP, you need to explicitly tell OpenMP how many threads to use.
export OMP_NUM_THREADS=${PBS_NP}

pwd
raxmlHPC -m GTRGAMMA -p 777 -s codon_alignment.fa -n tree_bootstrap -f a -x 778 -N 100 -T 20 
